apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    # change me! 
    # this should point to absolute path to this repo locally
    # since we are using docker container runtime, it requires us to specify absolute path.
    path: /Users/mm10444/Projects/streaming-platform/sp-connector-manager/scripts/security